# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
